### ISSUE TITLE
Problema para usar

### ISSUE THREAD

**Issue by fantastica** [taxweb/ruby_danfe#31]
**Olá Pessoal,** 

**Acabo de instalar essa gem, mas está apresentando o seguinte problema quando utilizo ela pelo irb tanto na versão do ruby 2.1.4 quanto na 1.9.3:**
2.1.4 :002 > RubyDanfe.generate("sample.pdf", "sample.xml")
NoMethodError: undefined method `strptime' for Time:Class
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/helper.rb:50:in`format_time'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/danfe_generator.rb:90:in `render_titulo'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/danfe_generator.rb:14:in`block in generatePDF'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/pdf-core-0.2.5/lib/pdf/core/page.rb:62:in `stamp_stream'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/prawn-1.0.0/lib/prawn/stamp.rb:83:in`create_stamp'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/prawn-1.0.0/lib/prawn/repeater.rb:99:in `initialize'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/prawn-1.0.0/lib/prawn/repeater.rb:79:in`new'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/prawn-1.0.0/lib/prawn/repeater.rb:79:in `repeat'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/document.rb:17:in`method_missing'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/danfe_generator.rb:11:in `generatePDF'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/ruby_danfe.rb:46:in`generatePDF'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/ruby_danfe.rb:20:in `render_file'
    from /home/carol/.rvm/gems/ruby-2.1.4/gems/ruby_danfe-1.11.5/lib/ruby_danfe/ruby_danfe.rb:7:in`generate'
    from (irb):2
    from /home/carol/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'

**Quando adiciono ela no meu projeto e tento subir o servidor, o seguinte erro é apresentado:**
/home/carol/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in `require': /home/carol/.rvm/gems/ruby-1.9.3-p392@athena/gems/ruby_danfe-0.9.0/lib/ruby_danfe.rb:119: invalid multibyte char (US-ASCII) (SyntaxError)
/home/carol/.rvm/gems/ruby-1.9.3-p392@athena/gems/ruby_danfe-0.9.0/lib/ruby_danfe.rb:119: invalid multibyte char (US-ASCII)
/home/carol/.rvm/gems/ruby-1.9.3-p392@athena/gems/ruby_danfe-0.9.0/lib/ruby_danfe.rb:119: syntax error, unexpected $end, expecting keyword_end
...2.00, 4.35, 1.27, "IDENTIFICAÇÃO E ASSINATURA DO RECEBEDOR"
...                               ^
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in `each'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in`block in require'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in `each'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in`require'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.7.4/lib/bundler.rb:133:in `require'
    from /home/carol/Projects/athena/config/application.rb:8:in`<top (required)>'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@athena/gems/railties-3.2.19/lib/rails/commands.rb:53:in `require'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@athena/gems/railties-3.2.19/lib/rails/commands.rb:53:in`block in <top (required)>'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@athena/gems/railties-3.2.19/lib/rails/commands.rb:50:in `tap'
    from /home/carol/.rvm/gems/ruby-1.9.3-p392@athena/gems/railties-3.2.19/lib/rails/commands.rb:50:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by jlneto** [comment]
Essa gem foi feita para ser usada dentro de um aplicativo Rails, pois ela requer várias bibliotecas.
Tente carregar as bibliotecas que ele reclamar:
Ex: require 'time' 

Quanto ao erro invalid multibyte char (US-ASCII) isso se deve aos acentos no ruby 1.9. veja no link abaixo uma solução
https://stackoverflow.com/questions/1739836/invalid-multibyte-char-us-ascii-with-rails-and-ruby-1-9
