### ISSUE TITLE
Barcode em cima da margem

### ISSUE THREAD

**Issue by romuloccomp** [taxweb/ruby_danfe#35]
Olá, eu instalei a gem e tudo funcionou muito bem.
Porém o código de barras ficou em cima da margem no lado direito.
![screen shot 2016-04-06 at 9 16 28 pm](https://cloud.githubusercontent.com/assets/498289/14336704/1074bb12-fc3d-11e5-8884-cfb08d9b5026.png)

**Comment by otaviomedeiros** [comment]
Romulo, por acaso a chave de acesso desta NF-e possui mais que 44 caracteres?
O manual da NF-e diz que chNFe(campo para o qual é criado o código de barra) possui até 44 caracteres e a gem cria o código considerando este limite.

**Comment by romuloccomp** [comment]
Oi Otávio, obrigado pelo retorno.
Conferi aqui, parece a chave tem apenas 44 chars. Porém na hora de gerar os 4 primeiro chars repedem no final, ex:

**8888**0601795809000110550010003856551393024529**8888**

Eu gero a parti de uma string, e conferi o chNFe e está correto.

**Comment by otaviomedeiros** [comment]
@romuloccomp o seu xml possui isto...
<chNFe>88880601795809000110550010003856551393024529</chNFe>
...e o pdf está sendo gerado com o campo _CHAVE DE ACESSO_ 8888 0601 7958 0900 0110 5500 1000 3856 5513 9302 4529 8888.

É isto que está acontecendo?

**Comment by romuloccomp** [comment]
Sim, no barcode e no texto abaixo dele.

**Comment by otaviomedeiros** [comment]
Testei uma NF-e aqui contendo `<chNFe>88880601795809000110550010003856551393024529</chNFe>`
e o código de barra e a chave de acesso ficaram ok. Olhando os códigos, não parece ter nada errado.

[https://github.com/taxweb/ruby_danfe/blob/master/lib/ruby_danfe/danfe_generator.rb#L65](url)

[https://github.com/taxweb/ruby_danfe/blob/master/lib/ruby_danfe/document.rb#L29](url)

**Comment by romuloccomp** [comment]
Muito estranho mesmo, olhei todo o código do app e da gem, e fiz um teste via arquivo com o irb. Só que persiste :(. Se você consegui verificar, segue o xml zipado.

Agradeço sua atenção.

**Ambiente:**
> Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)
> ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
> *** LOCAL GEMS ***
> ruby_danfe (1.11.5)

**Codigo:**
```
require 'ruby_danfe'
RubyDanfe.generate("sample.pdf", "31150689237911009601550000000576991653142092.xml")
```



[sample.pdf](https://github.com/taxweb/ruby_danfe/files/208822/sample.pdf)

[31150689237911009601550000000576991653142092.xml.zip](https://github.com/taxweb/ruby_danfe/files/208825/31150689237911009601550000000576991653142092.xml.zip)

**Comment by otaviomedeiros** [comment]
@romuloccomp este seu xml é uma mensagem de retorno e não uma NF-e.

`<retDownloadNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.00">`

Essa mensagem de retorno pode ter várias NF-es. Uma danfe é um documento auxiliar de uma NF-e.

Nesta linha de código [https://github.com/taxweb/ruby_danfe/blob/master/lib/ruby_danfe/danfe_generator.rb#L65](url)
você pode ver que a gem busca pelo elemento chNFe mas o seu xml tem dois elementos deste, por isso o código de barras e a chave de acesso ficam "duplicados". 

Você pode até alterar o código do danfe_generator para usar `@xml['nfeProc//chNFe']` ao invés de `@xml['chNFe']`. Isto resolveria o seu caso mas não sei o que aconteceria se o xml de retorno tiver mais de uma NF-e.

Acredito que só faz sentido danfe para NF-e e não para arquivo de retorno, o que você acha?

**Comment by romuloccomp** [comment]
@otaviomedeiros Você está completamente certo. Muito obrigado pelo retorno e desculpe o erro. Como estava espalhado no mesmo lugar os retornos e as NFe e ao gerar a DANFE funcionou quase tudo, nem me liguei nisso.
Obrigado novamente o parabéns pelo trabalho.
